apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: JLL-Design-System
  description: The JLL DS is a set of standards to manage design at scale by reducing redundancy while creating a shared language and visual consistency across different pages and channels.
  jll_pillar: Core
  jll_language: TypeScript
  jll_framework: JavaScript
spec:
  owner: JLL-DS-Team
  domain: Common Services
